import React, { ComponentType, useCallback, useState } from 'react'
import { Box, Button, Card, Flex, Text } from '@sanity/ui'
import { onKeyDownSelectCells } from '../utils/onKeyDownSelect'
import InitialiseGrid from './InitialiseGrid'
import { PortableTextBlock, SanityClient, useFormValue } from 'sanity'
import { RichTableCellType } from '../../../../schemaTypes/rich-table/cell.object'
import { RichTableRowType } from '../../../../schemaTypes/rich-table/row.object'
import { ColumnHeader } from '../../../../schemaTypes/rich-table/columnHeader.object'

type TableSize = { rows: number; cols: number }

interface InitialiseTableProps {
  maxRows?: number
  maxCols?: number
  client: SanityClient
  path: string
  _id: string
  // optional label or small help text
}

const CELL_SIZE = 28
const GAP = 6

const InitialiseTable: ComponentType<InitialiseTableProps> = ({
  maxRows = 10,
  maxCols = 10,
  client,
  path,
  _id,
}) => {
  const _type = useFormValue(['_type']) as string
  // * STATES
  const [selected, setSelected] = useState<TableSize>({
    rows: 0,
    cols: 0,
  })
  const [hover, setHover] = useState<TableSize>({ rows: 0, cols: 0 })

  const handleCommit = useCallback(
    async (rowCount: number, cols: number) => {
      setSelected({ rows: rowCount, cols: cols })
      // Prepare the initial table value
      // Cells per row
      const cells: Omit<RichTableCellType, '_key'>[] = Array.from({ length: cols ?? 1 }, () => {
        return {
          _type: 'richTableCell',
          content: [
            { _type: 'block', markDefs: [], children: [{ _type: 'span', text: '', marks: [] }] },
          ] as unknown as PortableTextBlock[],
        }
      })
      // New rows
      // @ts-ignore keys will be automatically generated by Sanity on commit
      const rows: Omit<RichTableRowType, '_key'>[] = Array.from({ length: rowCount ?? 1 }, () => ({
        _type: 'row',
        cells: cells,
      }))

      // New column header item (title uses current header count when available)
      const columnHeaders: Array<ColumnHeader & { _type: string }> = Array.from(
        { length: cols ?? 1 },
        (_, index) => ({
          _type: 'columnHeader',
          title: `New column ${index + 1}`,
          cellIndex: cols ? cols - 1 : 0,
        }),
      )
      // Commit the new table structure to Sanity
      await client
        .patch(_id)
        .set({ [path]: { rows, columnHeaders } })
        .commit({ autoGenerateArrayKeys: true })
        .then((res) => console.log(res))
        .catch(console.error)
    },
    [client, _id, selected],
  )
  // * COMMIT SELECTION
  const effectiveRows = selected.rows || hover.rows
  const effectiveCols = selected.cols || hover.cols

  return (
    <Card
      padding={3}
      border
      radius={4}
      tabIndex={0}
      onMouseLeave={() => setHover({ rows: 0, cols: 0 })}
      onKeyDown={(e) =>
        onKeyDownSelectCells({
          e,
          selected,
          setSelected,
          maxCols,
          maxRows,
          onChange: () => handleCommit(selected.rows, selected.cols),
        })
      }
      aria-label="Table size picker"
      style={{
        display: 'inline-block',
        userSelect: 'none',
      }}
    >
      <Flex justify={'center'}>
        <InitialiseGrid
          padding={4}
          $cellSize={CELL_SIZE}
          $gap={GAP}
          $maxHeight={Math.min(maxRows, 10) * (CELL_SIZE + GAP)}
          $maxWidth={Math.min(maxCols, 10) * (CELL_SIZE + GAP)}
          $maxRows={maxRows}
          $maxCols={maxCols}
        >
          {Array.from({ length: maxRows }).map((_, rIdx) =>
            Array.from({ length: maxCols }).map((__, cIdx) => {
              const rowCount = rIdx + 1
              const colCount = cIdx + 1
              const highlighted = rowCount <= effectiveRows && colCount <= effectiveCols
              const isSelected = rowCount <= selected.rows && colCount <= selected.cols
              return (
                <Button
                  key={`${rowCount}-${colCount}`}
                  onMouseEnter={() => setHover({ rows: rowCount, cols: colCount })}
                  onClick={() => {
                    handleCommit(rowCount, colCount)
                  }}
                  role="button"
                  aria-pressed={isSelected}
                  tone={highlighted ? 'primary' : 'default'}
                  mode={highlighted ? 'default' : 'ghost'}
                  style={{
                    width: CELL_SIZE,
                    height: CELL_SIZE,
                    boxSizing: 'border-box',
                  }}
                />
              )
            }),
          )}
        </InitialiseGrid>
      </Flex>
      <Flex align={'center'} justify={'space-around'} gap={3}>
        <Box>
          <Text size={1}>Selected: {`${hover.rows} × ${hover.cols}`}</Text>
        </Box>

        <Button
          onClick={() => {
            setSelected({ rows: 0, cols: 0 })
            setHover({ rows: 0, cols: 0 })
          }}
          mode={'bleed'}
          aria-label="Clear selection"
          fontSize={0}
          muted
          text={'Clear'}
        />
      </Flex>
    </Card>
  )
}
export default InitialiseTable
