// components/input/rich-table/hooks/useHandleAddColumn.tsx
import { useCallback } from 'react'
import type { SanityClient } from '@sanity/client'
import { Path, pathToString, PortableTextBlock } from 'sanity'
import { RichTableCellType } from '../../../../schemaTypes/rich-table/cell.object'
import { RichTableRowType } from '../../../../schemaTypes/rich-table/row.object'
import { ColumnHeader } from '../../../../schemaTypes/rich-table/columnHeader.object'

/**
 * Parameters for the `useHandleAddColumn` hook.
 */
interface UseHandleAddColumnParams {
  /** Sanity client instance for performing patches/transactions. */
  client: SanityClient
  /** Document ID in the Sanity dataset. */
  _id: string
  /** Path to the rich table inside the document. */
  path: Path
  /** Current rows value from the editor (may be undefined or empty). */
  value: RichTableRowType[] | undefined
  /** Current column headers array from the editor (may be undefined). */
  columnHeaders: ColumnHeader[] | undefined
  /** Maximum number of cells allowed (used to set the new header's index). */
  maxCellCountAllRows: number
}

/**
 * Custom hook returning a callback that appends a new column to a rich table.
 *
 * Behavior:
 * - If there are no rows, creates the first row (with a single cell) and ensures
 *   both `rows` and `columnHeaders` arrays exist via `setIfMissing`.
 * - Otherwise, appends one new cell to each existing row.
 * - Always appends a new column header item.
 * - Uses a Sanity transaction and `autoGenerateArrayKeys: true` so Sanity will
 *   generate `_key` values for new array items.
 *
 * @param params - Hook parameters (client, document id, path, current value/state).
 * @returns A stable callback `() => Promise<any>` that, when called, performs the Sanity transaction.
 */
export default function useHandleAddColumn({
  client,
  _id,
  path,
  value,
  columnHeaders,
  maxCellCountAllRows,
}: UseHandleAddColumnParams) {
  return useCallback(async () => {
    // Template for a new empty cell (no _key; Sanity will generate it)
    const newCellItem: Omit<RichTableCellType, '_key'> = {
      _type: 'richTableCell',
      content: [
        { _type: 'block', markDefs: [], children: [{ _type: 'span', text: '', marks: [] }] },
      ] as unknown as PortableTextBlock[],
    }

    // New column header item (title uses current header count when available)
    const newColumnHeaderItem: ColumnHeader & { _type: string } = {
      _type: 'columnHeader',
      title: `New column ${columnHeaders ? columnHeaders.length + 1 : ''}`,
      cellIndex: maxCellCountAllRows,
    }

    // If there are no rows yet, create the first row and set missing arrays
    if (!value || value.length === 0) {
      const firstRow: Omit<RichTableRowType, '_key'> = {
        _type: 'row',
        // @ts-ignore keys will be generated by Sanity on commit
        cells: [newCellItem],
      }

      // Ensure the table object with `rows` exists, and `columnHeaders` exists
      const setArrayPatch = client.patch(_id).setIfMissing({ [pathToString(path)]: { rows: [] } })
      const setColumnHeadersPatch = client
        .patch(_id)
        .setIfMissing({ [pathToString([...path, 'columnHeaders'])]: [] })

      // Append the first row and the initial column header
      const firstRowPatch = client
        .patch(_id)
        .append(`${pathToString([...path, 'rows'])}`, [firstRow])

      const addColumnToHeadersPatch = client
        .patch(_id)
        .append(`${pathToString([...path, 'columnHeaders'])}`, [newColumnHeaderItem])

      return await client
        .transaction()
        .patch(setArrayPatch)
        .patch(setColumnHeadersPatch)
        .patch(firstRowPatch)
        .patch(addColumnToHeadersPatch)
        .commit({ autoGenerateArrayKeys: true })
        .then((res) => console.info('Column successfully added', res))
        .catch((err) => console.error(err))
    }

    // For each existing row, append a new cell
    const transaction = client.transaction()
    value.forEach((_, rowIndex) => {
      const newCellPatch = client
        .patch(_id)
        .append(`${pathToString([...path, 'rows', rowIndex, 'cells'])}`, [newCellItem])
      transaction.patch(newCellPatch)
    })

    // Append the column header
    const addColumnToHeadersPatch = client
      .patch(_id)
      .append(`${pathToString([...path, 'columnHeaders'])}`, [newColumnHeaderItem])

    transaction.patch(addColumnToHeadersPatch)

    return await transaction
      .commit({ autoGenerateArrayKeys: true })
      .then((res) => console.info('Column successfully added', res))
      .catch((err) => console.error(err))
  }, [_id, path, value, columnHeaders, maxCellCountAllRows])
}
