import { useCallback } from 'react'
import { Path, pathToString, PortableTextBlock, SanityClient } from 'sanity'
import { RichTableCellType } from '../../../../schemaTypes/rich-table/cell.object'
import { RichTableRowType } from '../../../../schemaTypes/rich-table/row.object'

/**
 * Parameters for the `useHandleAddRow` hook.
 */
interface UseHandleAddRowParams {
  /** Sanity client instance for interacting with the database. */
  client: SanityClient
  /** Document ID in the Sanity dataset. */
  _id: string
  /** Path to the rich table in the document. */
  path: Path
  /** Maximum number of cells present in all rows. */
  maxCellCountAllRows: number
}

/**
 * Custom hook to handle adding a new row to a rich table in a Sanity document.
 *
 * @param {UseHandleAddRowParams} params - The parameters for the hook.
 * @returns {() => Promise<void>} - A callback function to add a new row.
 */
export default function useHandleAddRow({
  client,
  _id,
  path,
  maxCellCountAllRows,
}: UseHandleAddRowParams) {
  return useCallback(async () => {
    // Create an array of empty cells for the new row.
    const cells: Omit<RichTableCellType, '_key'>[] = Array.from(
      { length: maxCellCountAllRows ?? 1 },
      () => {
        return {
          _type: 'richTableCell',
          content: [
            { _type: 'block', markDefs: [], children: [{ _type: 'span', text: '', marks: [] }] },
          ] as unknown as PortableTextBlock[],
        }
      },
    )

    // Define the new row with the generated cells.
    const newRow: Omit<RichTableRowType, '_key'> = {
      _type: 'row',
      // @ts-ignore keys will be automatically generated by Sanity on commit
      cells: cells,
    }

    // Create a patch to ensure the rows array exists in the document.
    const setArrayPatch = client.patch(_id).setIfMissing({ [pathToString(path)]: { rows: [] } })

    // Define the path to the rows array and create a patch to append the new row.
    const rowsPath = pathToString([...path, 'rows'])
    const newRowPatch = client.patch(_id).append(rowsPath, [newRow])

    // Execute the transaction to add the new row.
    return await client
      .transaction()
      .patch(setArrayPatch)
      .patch(newRowPatch)
      .commit({ autoGenerateArrayKeys: true })
      .then((res: any) => console.info('Row successfully added', res))
      .catch((err: any) => console.error(err))
  }, [_id, path, maxCellCountAllRows])
}
