import { RichTableType } from '../../rich-table/RichTableInput'
import { PortableTextBlock, SanityClient } from 'sanity'
import { useCallback } from 'react'
import { RichTableCellType } from '../../../../schemaTypes/rich-table/cell.object'
import { RichTableRowType } from '../../../../schemaTypes/rich-table/row.object'

interface UseAddRowProps {
  /** Sanity client instance for interacting with the database. */
  client: SanityClient
  /** Document ID in the Sanity dataset. */
  _id: string
  /** Path to the rich table in the document. */
  path: string
  /** Current value of the rich table object */
  value: RichTableType
}

export default function useAddRow({ client, _id, path, value }: UseAddRowProps) {
  return useCallback(async () => {
    const colCount = value?.columnHeaders?.length || 0
    // Create an array of empty cells for the new row.
    const cells: Omit<RichTableCellType, '_key'>[] = Array.from({ length: colCount ?? 1 }, () => {
      return {
        _type: 'richTableCell',
        content: [
          { _type: 'block', markDefs: [], children: [{ _type: 'span', text: '', marks: [] }] },
        ] as unknown as PortableTextBlock[],
      }
    })

    // Define the new row with the generated cells.
    const newRow: Omit<RichTableRowType, '_key'> = {
      _type: 'row',
      // @ts-ignore keys will be automatically generated by Sanity on commit
      cells: cells,
    }

    // Create a patch to ensure the rows array exists in the document.
    const setArrayPatch = client.patch(_id).setIfMissing({ [path]: { rows: [] } })
    // Define the path to the rows array and create a patch to append the new row.
    const rowsPath = path + '.rows'
    const newRowPatch = client.patch(_id).append(rowsPath, [newRow])

    // Execute the transaction to add the new row.
    return await client
      .transaction()
      .patch(setArrayPatch)
      .patch(newRowPatch)
      .commit({ autoGenerateArrayKeys: true })
      .then((res: any) => console.info('Row successfully added', res))
      .catch((err: any) => console.error(err))
  }, [client, _id, path, value])
}
